# Generated by Django 5.2 on 2025-04-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_localcheck_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='price',
        ),
    ]
